// Required post-deployment integrity check, no pipeline/model calls.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const root='/data/output/ias-linkedin',dir=process.argv[2],hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const oldArchives=JSON.parse(fs.readFileSync(dir+'/archive-before.private.json'));for(const [p,h]of Object.entries(oldArchives))assert.equal(hash(fs.readFileSync(p)),h,'Existing archive changed');
const current=JSON.parse(fs.readFileSync(root+'/current-status.json')),before=JSON.parse(fs.readFileSync(dir+'/current-before.private.json'));assert.notEqual(current.cycleHash,before.cycleHash);assert.equal(current.files.length,5);
for(const f of current.files){assert.equal(hash(fs.readFileSync(root+'/'+f.fileName)),f.sha256);assert.equal(hash(fs.readFileSync(path.resolve(root,current.archive,f.fileName))),f.sha256);}
const candidateFile=current.files.find(x=>x.fileName.startsWith('content-candidates')).fileName,planFile=current.files.find(x=>x.fileName.startsWith('linkedin-editorial-plan')&&x.fileName.endsWith('.json')).fileName;
const c=JSON.parse(fs.readFileSync(root+'/'+candidateFile)),p=JSON.parse(fs.readFileSync(root+'/'+planFile));assert.equal(c.evidencePolicyVersion,'1.0');assert.equal(p.policySummary.automaticPublishingAllowed,false);assert.equal(p.sourceCandidateFile,candidateFile);
const {gate}=require(root+'/evidence/policy.cjs');
for(const item of c.themeAligned){const packet={sources:item.sources,shortlist:[{id:item.evidenceBundleId,topic:item.topic,sourceIds:item.sources.map(s=>s.id)}]},response={sourceAssessments:c.sourceAssessments,candidates:[{id:item.evidenceBundleId,decision:'accept',claims:item.claims}]};assert(gate(packet,response).rows[0].accepted,'Accepted item fails deployed gate');for(const s of item.sources){assert(s.cacheFile);const cached=JSON.parse(fs.readFileSync(root+'/'+s.cacheFile));assert.equal(cached.textSha256,s.textSha256);for(const cp of s.passages)assert(cached.passages.some(x=>x.id===cp.id&&x.text===cp.text));}}
assert(p.selectedTopics.every(t=>c.themeAligned.some(c=>c.topic===t.sourceCandidateTopic)&&t.humanReviewRequired===true));
console.log(JSON.stringify({passed:true,completedAt:current.completedAt,cycleHash:current.cycleHash,archive:current.archive,files:current.files.map(f=>f.fileName),oldArchiveFilesUnchanged:Object.keys(oldArchives).length,diagnostics:c.diagnostics,selectedTopics:p.selectedTopicCount,reviewFlags:p.selectedTopics.map(t=>({topic:t.sourceCandidateTopic,unmappedProse:t.fullProseReview?.assertions?.filter(a=>a.status==='human_review_required').length,webinarReview:t.webinarReview})),publishingDisabled:true}));
